#!/usr/bin/env bash

#HarchPost - Post install - Downloadeded after Harch finishes
# ---------------------------------------------------------------
# Author    : Chaotic_Guru                                       |
# Github    : https://github.com/ChaoticHackingNetwork           |
# Discord   : https://discord.gg/nv445EX (ChaoticHackingNetwork) |
# Version   : 0.1.0												 |
# ---------------------------------------------------------------

GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[0;37m'
YELLOW='\033[0;33m'
PURPLE='\033[0;35m'
RESET='\033[0m'
NEWLINE=$'\n'

installer() {
	#Installs needed packages
	echo -e "${GREEN}[*] Installing packages...${RESET}"
	echo -e "${YELLOW}[!] Adding Mate/i3 DE${RESET}"
	pacman -S dhcpcd iwd mlocate cmake neofetch grub pulseaudio git terminator zsh fish dconf-editor leafpad ntfs-3g xorg xorg-server xorg-xinit xterm mate mate-extra i3-gaps i3status lightdm lightdm-gtk-greeter --noconfirm
	systemctl enable lightdm
}


sublimeInstaller() {
	echo -e "${GREEN}Installing Sublime Text...${RESET}"
	curl -O https://download.sublimetext.com/sublimehq-pub.gpg && pacman-key --add sublimehq-pub.gpg && pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
	sleep 3
	echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | tee -a /etc/pacman.conf
	sleep 3
	pacman -Syu sublime-text --noconfirm
}

vidDriver() {
	echo ${NEWLINE}
	echo ${NEWLINE}
	echo -e "${GREEN}[*] Gathering Graphics info...${RESET}"
	GPU=$(lspci -v | grep -A 2 -E "(VGA|3D)")
	echo -e "${YELLOW}$GPU${RESET}"
	echo ${NEWLINE}
	read -p "[!] What is your GPU: [amd] [nvidia] or [intel]: " video
	if [[ $video == amd ]] 
	then
	pacman -S xf86-video-ati xf86-video-fbdev mesa --noconfirm
	elif [[ $video == nvidia ]]
	then
	pacman -S nvidia nvidia-settings --noconfirm
	else [[ $video == intel ]]
	pacman -S xf86-video-intel xf86-video-fbdev mesa intel-ucode --noconfirm
	    
	fi
}

userInfo() {
	#Set root password
	echo -e "${YELLOW}[!] Please set ROOT password!!!${RESET}"
	passwd

	#Create a new user
	read -p "[*] Enter a new Username: " username
	echo -e "${GREEN}[*] Welcome to your new system $username!${RESET}"
	useradd -mg users -G wheel,power,storage,uucp,network -s /usr/bin/fish $username
	echo -e "${YELLOW}[!] Please set your password now!${RESET}"
	passwd $username
	perl -i -pe 's/# (%wheel ALL=\(ALL\) ALL)/$1/' /etc/sudoers
}

booter() {
	echo ${NEWLINE}
	echo ${NEWLINE}
	echo -e "${GREEN}[*] Setting Booterloader...${RESET}"
	drives=$(lsblk -f)
	echo -e "${YELLOW}$drives${RESET}${NEWLINE}"
	read -p "Enter Drive to install Booterloader [Example: /dev/nvme01p1]: " drive
	ls /sys/firmware/efi
	if [[ -d "/sys/firmware/efi" ]]
	then
	pacman -S efibootmgr dosfstools mtools os-prober --noconfirm
	grub-install --target=x86_64-efi --bootloader-id=HARCH_UEFI --efi-directory=/boot/EFI --recheck
	grub-mkconfig -o /boot/grub/grub.cfg
	else
	grub-install --target=i386-pc $drive --recheck
	grub-mkconfig -o /boot/grub/grub.cfg

	fi
}

blackArch() {
	#Install BlackArch Mirror & download tools list
	echo -e "${GREEN}Installing BlackArch Repo... HANG TIGHT!!!${RESET}"
	curl -O https://blackarch.org/strap.sh
	chmod +x strap.sh
	./strap.sh /dev/null 2>&1
	
}


complete() {
	#Successfully Installed
	neofetch
	echo -e "${GREEN}[!] Harch has been succesfully installed on your system"
	echo""
	echo -e "Hack the Universe $username${RESET}"
	echo""
	echo""
	echo -e "${YELLOW}[!] A reboot should now take place"
	echo "[!] Run the following commands to reboot properly!"
	echo""
	echo  "[1]: exit"
	echo  "[2]: umount -a"
	echo -e "[3]: reboot${RESET}"

	exit
}


installer
sleep 5
clear
userInfo
sleep 5
clear
vidDriver
sleep 5
clear
booter
sleep 5
clear
blackArch
sleep 5
clear

read -p "Do you want to install Sublime Text? [y/n]: " subl
if [[ $subl == 'y' ]]
then
sublimeInstaller
sleep 3
clear
else
continue

fi

complete
