#!/bin/bash
#HarchPost 
# ---------------------------------------------------------------
# Author    : Chaotic_Guru                                       |
# Github    : https://github.com/ChaoticHackingNetwork           |
# Discord   : https://discord.gg/nv445EX (ChaoticHackingNetwork) |
# ---------------------------------------------------------------

#Install some needed packages
pacman -S vim nano dhcpcd iwd wpa_supplicant mlocate grub neofetch firefox chromium terminator konsole net-tools dnsutils ntfs-3g sudo man-db usbutils pulseaudio alsa-utils pyenv python2 python3 nvidia --noconfirm

#Set root password
echo -e "\033[33;36mPlease set ROOT password!!!\033[0m"
passwd

#Create a new user
read -p "Enter a new Username: " username
echo "Welcome to your new system $username!"
useradd -mg users -G wheel,power,storage,uucp,network -s /bin/bash $username
echo -e "\033[33;36mPlease set your password now!\033[0m"
passwd $username
perl -i -pe 's/# (%wheel ALL=\(ALL\) ALL)/$1/' /etc/sudoers

# Set locale to en_US.UTF-8 UTF-8
sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

#Set time & clock
timedatectl set-ntp true
hwclock --systohc --utc

#Change localtime *Note this script has it set too Chicago*
ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime #CHANGE THIS TO YOUR TIMEZONE

#Install MATE Desktop env and LightDM after reboot
pacman -S xorg xorg-xdm mate mate-extra --noconfirm
systemctl enable xdm

#Install bootloader
ls /sys/firmware/efi
if [[ -d "/sys/firmware/efi" ]]
then
pacman -S efibootmgr dosfstools mtools os-prober --noconfirm
mkdir /boot/EFI
mount /dev/sda1 /boot/EFI
grub-install --target=x86_64-efi --bootloader-id=HARCH_UEFI --recheck
grub-mkconfig -o /boot/grub/grub.cfg
else
grub-install --target=i386-pc /dev/sda --recheck
grub-mkconfig -o /boot/grub/grub.cfg

fi

#Install BlackArch Mirror & download tools list
curl -O https://blackarch.org/strap.sh
chmod +x strap.sh
./strap.sh
pacman -Syyu --noconfirm
curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/Harch/main/Tools/Master
cd /home/$username
mkdir Desktop
mv Master-toolList home/$username/Desktop

#Successfully Installed
neofetch
echo "Harch has been succesfully installed on your system"
echo "Hack the planet $username"
echo "A reboot should now take place"
echo "Run the following commands to reboot properly!"
echo
echo -e "\033[33;36m[1]: exit\033[0m"
echo -e "\033[33;36m[2]: umount -a\033[0m"
echo -e "\033[33;36m[3]: telinit 6\033[0m"

exit 
