#!/bin/bash

# Harch UEFI/Bios Install (Hackers Arch)
# ---------------------------------------------------------------
# Author    : Chaotic_Guru                                       |
# Github    : https://github.com/ChaoticHackingNetwork           |
# Discord   : https://discord.gg/nv445EX (ChaoticHackingNetwork) |
# ---------------------------------------------------------------

GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[0;37m'
YELLOW='\033[0;33m'
PURPLE='\033[0;35m'
RESET='\033[0m'

echo -e "${GREEN}Chaotic_Guru's Harch Installer${RESET}"
echo""
echo "╔╗ ╔╗            ╔╗      ╔╗                 "
echo "║║ ║║            ║║      ║║                 "
echo "║╚═╝║╔══╗ ╔═╗╔══╗║╚═╗    ║║   ╔╗╔═╗ ╔╗╔╗╔╗╔╗"
echo "║╔═╗║╚ ╗║ ║╔╝║╔═╝║╔╗║    ║║ ╔╗╠╣║╔╗╗║║║║╚╬╬╝"
echo "║║ ║║║╚╝╚╗║║ ║╚═╗║║║║    ║╚═╝║║║║║║║║╚╝║╔╬╬╗"
echo "╚╝ ╚╝╚═══╝╚╝ ╚══╝╚╝╚╝    ╚═══╝╚╝╚╝╚╝╚══╝╚╝╚╝"
echo""
echo""
echo""
                                                      
#Network Connections
read -p 'Are you connected to the Internet? [y/N]: ' connected
if ! [ $connected = 'y' ] && ! [ $connected = 'Y' ]
then
	echo -e "${RED}Please connect to the Internet to continue...${RESET}"
	exit
fi

read -p 'This script is by default modifying /dev/sda, ensure this is the drive you want, Continue? [y/N]:' device
if ! [ $device = 'y' ] && ! [ $device = 'Y']
then
	echo -e "${RED}Change your partition via the script${RESET}"
	exit
fi

#Determine BIOS or UEFI
ls /sys/firmware/efi
if [[ -d "/sys/firmware/efi" ]]
then
echo -e "${YELLOW}UEFI was determined!${RESET}"
echo"" 
echo "This script will create and format the following partitions:"
echo "/dev/sda1 - 512M will be mounted as /boot/EFI"
echo "/dev/sda2 - 16G of space will be mounted as SWAP"
echo "/dev/sda3 - rest of space will be mounted as /"
echo""
echo "Exit now if this is not correct!!!"
sleep 10s
#Create partitions thru fdisk...
#https://superuser.com/a/984637
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/sda #CHANGE THIS IF NEEDED!!!
o # Clear the in-memory partition table
n # New partition
p # Primary partition
1 # First partition
	# EFI - start at beginning of disk
+512M # /boot/EFI
n
p
2
	# SWAP - start immediately after preceding partition
+16G
n 
p
3
	# ROOT, start immediately after preceding partition
	# default, use rest of disk space
p # print the in-memory table
w # write changes to disk
q # quit
EOF

	#Format partitions
	mkfs.ext4 /dev/sda3 
	mkfs.fat -F32 /dev/sda1

	#Mount partitions
	mount /dev/sda3 /mnt

	#Create swap space
	mkswap /dev/sda2
	swapon /dev/sda2

else
echo -e "${YELLOW}BIOS was determined!${RESET}" 
echo "This script will create and format the following partitions:"
echo ""
echo "/dev/sda1 - 16G will be mounted as SWAP space"
echo "/dev/sda2 - Rest of space will be mounted as /"
echo "Exit now if this is not correct!!!"
sleep 10s
echo""
#Create partitions thru fdisk...
#https://superuser.com/a/984637
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/sda # CHANGE THIS IF NEEDED!!!
o # Clear the in-memory partition table
n # New partition
p # Primary partition
1 # First partition
	# SWAP - start at beginning of disk
+16G # swap space
n 
p
2
	# ROOT, start immediately after preceding partition
	# default, use rest of disk space
p # print the in-memory table
w # write changes to disk
q # quit
EOF

	#Format partitions
	mkfs.ext4 /dev/sda2

	#Mount partitions
	mount /dev/sda2 /mnt

	#Create swap space
	mkswap /dev/sda1
	swapon /dev/sda1

fi

#Install base system
pacstrap /mnt base base-devel linux linux-firmware

#Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab
lsblk
echo "Finishing last minute setup..."
sleep 3

#Finish last minute setup
echo 0 > /proc/sys/kernel/hung_task_timeout_secs
curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/Harch/main/HarchPOST
mv HarchPOST /mnt
echo""
echo "The final script has been installed and move to your new root directory"
echo "Run these commands to finish setup"
echo""
echo""
echo -e "${PURPLE}[1] arch-chroot /mnt${RESET}"
echo -e "${PURPLE}[2] chmod +x HarchPost.sh${RESET}"
echo -e "${PURPLE}[3] ./HarchPost.sh${RESET}"
echo""

exit
