#!/usr/bin/env bash

#hArchPost - Post install - Downloadeded after hArch finishes
# ---------------------------------------------------------------
# Author    : Chaotic_Guru                                       |
# Github    : https://github.com/ChaoticHackingNetwork           |
# Version   : 1.0.0                                              |
# ---------------------------------------------------------------


# Color Constants
GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[0;37m'
YELLOW='\033[0;33m'
PURPLE='\033[0;35m'
RESET='\033[0m'
NEWLINE=$'\n'

# Logging Functions
log_info() { echo -e "[${GREEN}INFO${RESET}] $1"; }
log_warning() { echo -e "[WARNING] $1"; }
log_error() { echo -e "[ERROR] $1"; }
print_info() { echo -e "[${YELLOW}INFO${RESET}] $1${NEWLINE}"; }
log_success() { echo -e "[SUCCESS] $1"; }

# Prompt for User Input
prompt_for_input() {
    read -p "$1" response
    echo "$response"
}

installer() {
    print_info "What would you like your system name set too..."
    hostname=$(prompt_for_input "Enter Hostname: ")
    echo $hostname > /etc/hostname
    log_info "Installing some handy packages..."
    pacman -S dkms linux-headers iwd mlocate cmake ntp neofetch pulseaudio net-tools dnsutils git fish noto-fonts ttf-ubuntu-font-family ttf-dejavu ttf-freefont ttf-liberation ttf-droid ttf-roboto terminus-font rxvt-unicode ranger rofi dmenu --needed --noconfirm
    hwclock --systohc
}

desktopEnv() {
    log_info "Choose a Desktop Environment"
    log_info "Select number corresponding to DE you want, after installation enter 8 to continue if prompt returns${NEWLINE}"
    
    DEs=("Mate" "KDE" "Gnome" "Cinnamon" "Deepin" "Enlightenment" "i3" "Skip")
    select opt in "${DEs[@]}"
    do
        case $opt in
            "Mate") install_desktop "mate mate-extra lightdm lightdm-gtk-greeter" "lightdm" ;;
            "KDE") install_desktop "plasma plasma-wayland-session kde-applications" "sddm" ;;
            "Gnome") install_desktop "gnome gnome-extra lxdm" "lxdm" ;;
            "Cinnamon") install_desktop "cinnamon gnome-terminal lxdm" "lxdm" ;;
            "Deepin") install_desktop "deepin deepin-extra lightdm" "lightdm" ;;
            "Enlightenment") install_desktop "enlightenment terminology lxdm" "lxdm" ;;
            "i3") install_desktop "i3-gaps i3blocks i3lock numlockx gdm" "gdm" ;;
            "Skip") break ;;
            *) log_error "Invalid Option, Try Again..." ;;
        esac
        print_info "Select number corresponding to DE you want, after installation enter 8 to continue if prompt returns"
    done
}

install_desktop() {
    packages="$1"
    display_manager="$2"
    pacman -S $packages xorg xorg-server xorg-apps xorg-xinit --needed --noconfirm
    if [[ $packages == *"deepin"* ]]; then
    sed -i '/^greeter-session=/c\greeter-session=lightdm-deepin-greeter' /etc/lightdm/lightdm.conf
    fi
    handle_nvidia
    systemctl enable $display_manager
}

handle_nvidia() {
    NVD='NVIDIA'
    card=$(lspci -vmm | grep VGA -A6)
    if [[ $card == *"$NVD"* ]]; then
        log_info "Nvidia graphics detected. Applying configuration..."
        # Add Nvidia-specific configurations here
        # This will replace vidDriver() NVD case
    fi
}

vidDriver() {
    log_info "Gathering Graphics info..."
    sleep 2
    str=$(lspci -vmm | grep VGA -A6)
    AMD='AMD'
    NVD='NVIDIA'
    case $str in
        *"$AMD"*)
            log_info "Installing AMD Drivers..."
            pacman -S xf86-video-ati xf86-video-amdgpu mesa --noconfirm
            ;;
        *"$NVD"*)
            log_info "Installing NVIDIA Drivers..."
            pacman -S nvidia nvidia-settings nvidia-utils glxinfo nvtop --noconfirm
            curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/nvidia.hook
            curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/20-nvidia.conf
            mv nvidia.hook /etc/pacman.d/hooks
            mv 20-nvidia.conf /etc/X11/xorg.conf.d/
            bash -c "echo blacklist nouveau > /etc/modprobe.d/blacklist-nvidia-nouveau.conf"
            # FIXME
            # Add changes to mkinitcpio.conf - WIP
            # If issues, try:
            # xrandr --setprovideroutputsource modesetting NVIDIA-0
            # xrandr --auto
            ;;
        *)
            log_info "Unable to determine Graphics info.. Installing default drivers"
            pacman -S xf86-video-fbdev --noconfirm
    esac
}

userInfo() {
    log_info "Setting Root password..."
    passwd

    username=$(prompt_for_input "Enter Username: ")
    log_info "Creating a new user: $username"
    useradd -mg users -G wheel,power,storage -s /usr/bin/fish $username
    echo '%wheel ALL=(ALL:ALL) ALL' >> /etc/sudoers.d/wheel_group
    chmod 440 /etc/sudoers.d/wheel_group
    log_info "Setting password for user: $username"
    passwd $username
}

booter() {
    log_info "Setting Bootloader..."
    drives=$(lsblk -f)
    echo -e "$drives${NEWLINE}"
    echo -e "[${YELLOW}SYNTAX${RESET}] If BIOS, attach bootloader to disk: ex- /dev/sda"
    echo -e "[${YELLOW}SYNTAX${RESET}] If UEFI, attach bootloader to partition: ex- /dev/nvme0n1p1"
    drive=$(prompt_for_input "Enter Drive to install Bootloader [Example: /dev/nvme0n1p1]: ")
    if [[ -d "/sys/firmware/efi" ]]; then
        log_info "Installing UEFI Bootloader..."
        pacman -S efibootmgr grub dosfstools mtools os-prober --noconfirm
        grub-install --target=x86_64-efi --bootloader-id=HARCH_UEFI --efi-directory=/boot/EFI --recheck
        grub-mkconfig -o /boot/grub/grub.cfg
        mkinitcpio -p linux
    else
        log_info "Installing BIOS Bootloader..."
        pacman -S grub --noconfirm
        grub-install --target=i386-pc $drive --recheck
        grub-mkconfig -o /boot/grub/grub.cfg
        mkinitcpio -p linux
    fi
}

blackArch() {
    log_info "Installing BlackArch Repo..."
    curl -O https://blackarch.org/strap.sh
    chmod +x strap.sh
    ./strap.sh
    sleep 3
    pacman -Syu --noconfirm
}

vimSetup() {
    vim=$(prompt_for_input "Do you want to add Bundle to VIM? [y/n]: ")
    if [[ $vim == 'y' || $vim == 'Y' ]]; then
        log_info "Adding Bundle to VIM..."
        users=$(ls /home)
        curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/vimrc_bundle_conf
        mv vimrc_bundle_conf /home/$users/.vimrc
    else
        log_warning "Skipping..."
    fi
}

hackTools() {
    ht=$(prompt_for_input 'Do you want to add the Master Hacking Toolset? [y/n]: ')
    if [[ $ht == 'y' || $ht == 'Y' ]]; then
        log_info "Installing Master Hacking Toolset..."
        curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/Tools/Master
        curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/Tools/useful-packages
        pacman -S - < /Master --noconfirm && pacman -S - < /useful-packages --noconfirm
    else
        log_warning "Skipping..."
        curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/Tools/Master
        curl -O https://raw.githubusercontent.com/ChaoticHackingNetwork/hArch/main/Tools/useful-packages
    fi
}

complete() {
    log_success "hArch has been successfully installed on your system"
    neofetch
    log_info "Hack the Universe $username"
    log_info "A reboot should now take place"
    log_info "Run the following commands to reboot properly:"
    log_info "1: exit"
    log_info "2: umount -a"
    log_info "3: reboot"
    exit
}

sleep_and_clear() {
    sleep 3
    clear
}

oneFuncToRuleThemAll() {
    installer
    sleep_and_clear

    userInfo
    sleep_and_clear

    vidDriver
    sleep_and_clear

    booter
    sleep_and_clear

    blackArch
    sleep_and_clear

    hackTools
    sleep_and_clear

    vimSetup
    sleep_and_clear

    desktopEnv
    sleep_and_clear

    complete
}



oneFuncToRuleThemAll
